language: perl
perl:
    - '5.20'
env:
    - BACKEND=moar
matrix:
    fast_finish: true
sudo: false
before_install:
    - git clone https://github.com/tony-o/perl6-travis-bin.git bins
    - mv bins/brew ~/
    - eval "$($HOME/brew/bin/rakudobrew init -)"
install:
    # need at least 1 statement in 'install'
    - perl6 -v
script:
    - prove -e 'perl6 -Ilib' t/
