version: 7.5.0-{build}

clone_depth: 50

environment:
  MS_SDK_VER: v7.1
  matrix:
  - CPU: x86
    BLD: debug
  - CPU: x86
    BLD: release
  - CPU: x64
    BLD: debug
  - CPU: x64
    BLD: release

install:
  - cmd: '"C:\Program Files\Microsoft SDKs\Windows\%MS_SDK_VER%\Bin\SetEnv.cmd" /%CPU% /%BLD%'

build_script:
  - cmd: cd src && nmake -f Makefile.msft clean all && cd ..

test_script:
  - cmd: cd src && nmake -f Makefile.msft test_malloc test_stack
