language: "java"
    
sudo: false
dist: trusty

install: "echo"

script: "perl Configure.pl $NQP_OPTIONS; make test"

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#perl6-dev"
    on_success: change
    on_failure: always
    template:
      - "NQP build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"


env:
  matrix:
    - NQP_OPTIONS="--gen-moar"
    - NQP_OPTIONS="--gen-moar=master"
    - NQP_OPTIONS="--backends=jvm"

#matrix:
#  allow_failures:
#    - env: NQP_OPTIONS="--backends=jvm"
