#!/bin/sh
exec /home/travis/brew/moar-nom/install/bin/moar  --execname="$0" --libpath="/home/travis/brew/moar-nom/install/share/nqp/lib" --libpath="." /home/travis/brew/moar-nom/perl6-debug.moarvm "$@"
